### ISSUE TITLE
`dust` is listed twice

### ISSUE THREAD

**Issue by bfrg** [toolleeo/cli-apps#10]
`dust` is listed twice under [Disk usage analyzers](https://github.com/toolleeo/cli-apps#disk-analyzer):

[Dust](https://github.com/bootandy/dust) - du + rust = dust. Like du but more intuitive.
[Dust](https://github.com/bootandy/dust) - A more intuitive version of du in rust.

Both point to the same project.

**Comment by toolleeo** [comment]
Fixed, thanks very much!
