### ISSUE TITLE
New Project - Redo.vc

### ISSUE THREAD

**Issue by sottey** [toolleeo/cli-apps#31]
A complete task/todo manager with a CLI interface. Advanced features like http serving, bulk editing, tagging, full text search, theming and more!

**name**: Redo.vc
**homepage**: https://redo.vc
**git**: https://github.com/sottey/redo.vc
**description**: 
Redo.vc is a tool for command line fans that allows you to track your tasks. It is a full featured todo manager with tagging, projects, recurring tasks and much more, all stored in a JSON file so it is super portable and tooling new apps for the data format is super easy.

Thanks!
Sean

**Comment by toolleeo** [comment]
Added. Thanks for the great suggestion.
