### ISSUE TITLE
ascii-matrix

### ISSUE THREAD

**Issue by christosangelopoulos** [toolleeo/cli-apps#33]
## ascii-matrix

[https://gitlab.com/christosangel/ascii-matrix](https://gitlab.com/christosangel/ascii-matrix)

This script written in the C language, will render the matrix effect in the
terminal, while rendering ascii art loaded from a txt file,
at the center of the terminal window.

![zoidberg](https://gitlab.com/christosangel/ascii-matrix/-/raw/main/gif/zoidberg.gif)

**Comment by toolleeo** [comment]
Added! Thanks for the contribution.
