### ISSUE TITLE
tui-sudoku

### ISSUE THREAD

**Issue by christosangelopoulos** [toolleeo/cli-apps#34]
# tui-sudoku

[https://gitlab.com/christosangel/tui-sudoku](https://gitlab.com/christosangel/tui-sudoku)

**tui-sudoku** is a *configurable* terminal interface sudoku game, with *quite a few features*.

![https://gitlab.com/christosangel/tui-sudoku/-/raw/main/screenshots/5.png](https://gitlab.com/christosangel/tui-sudoku/-/raw/main/screenshots/5.png)

P.S.: I noticed that there was no sudoku game in your collection, so I thought it might interest you.

**Comment by toolleeo** [comment]
Added to the list.
Thanks for the suggestion!
