### ISSUE TITLE
gentoo-install

### ISSUE THREAD

**Issue by hendrack** [toolleeo/cli-apps#35]
https://github.com/oddlama/gentoo-install

"This project aspires to be your favourite way to install gentoo. It aims to provide a smooth installation experience, both for beginners and experts. You may configure it by using a menuconfig-inspired interface or simply via a config file."

![screenshot_configure](https://github.com/toolleeo/cli-apps/assets/23265970/9dd01e8f-c425-4846-b1c9-1bedad680aae)

**Comment by toolleeo** [comment]
Very nice tool.
Thanks for the suggestion.
