### ISSUE TITLE
PMT

### ISSUE THREAD

**Issue by olexij-christian** [toolleeo/cli-apps#47]
# PMT

https://github.com/olexij-christian/pmt

PMT - translator of package names between different package managers of Linux distributions, such as apt or dnf. 🚀

My first Bash project, what do you think? I think it will fit nicely into the Package managers category! ☺️

**Comment by toolleeo** [comment]
Yes, nice, thanks.

Do you want to contribute with a pull request, so to prove your contribution in the project, or do you prefer that I add it to the list myself?

**Comment by olexij-christian** [comment]
Okay, I'll do it

**Comment by toolleeo** [comment]
PMT is now included in the list, tks.
