### ISSUE TITLE
mailsy

### ISSUE THREAD

**Issue by zamb0** [toolleeo/cli-apps#59]
`name`: mailsy
`homepage`: https://github.com/BalliAsghar/Mailsy
`git`: https://github.com/BalliAsghar/Mailsy.git
`description`: generates disposable emails in the cli through [mail.tm](https://mail.tm)

**Comment by zamb0** [comment]
could be a possible alternative to tmpmail

> [tmpmail](https://github.com/sdushantha/tmpmail) - A command line utility written in POSIX sh that allows you to create a temporary email address and receive emails to the temporary email address.

**Comment by toolleeo** [comment]
Thanks for the contribution.
Do you want to open a pull request (to get the credits of the addition), or  do you prefer that I add it to the list myself?

**Comment by zamb0** [comment]
i'll try to open a pull request following these guidelines, thanks 
> The peculiarity of this repository is that the source of information is structured into CSV files with a simple structure. See the data/ directory.
If you want to contribute using a pull request, add the new entry to data/apps.csv. In the CSV file, the git field refers to a clonable git URL.
Please make changes to the CSV file only, not to the README file. I will review the request and, upon acceptance, I will take care of generating the README and updating the list.
