### ISSUE TITLE
Adding pyutube

### ISSUE THREAD

**Issue by Hetari** [toolleeo/cli-apps#68]
## pyutube
https://github.com/Hetari/pyutube

`pyutube` is a simple cli tool to download YouTube video shorts and playlist

## why pyutube?
While `youtube-dl` offers robust features and configurability, `pyutube` distinguishes itself through simplicity and ease of use. `pyutube` simplifies the process, with no need to delve into complex configurations or documentation, such as identifying specific options for downloading audio-only, but in `pyutube` just paste the URL and that's it 

I hope that you found the tool helpful! If you enjoyed using it, why not consider adding it to your list? And if it didn't hit the spot, no worries. Feel free to let me know how I can improve it in the future. Thanks so much for trying it out!

**Comment by toolleeo** [comment]
Hi, I will be happy to add this tool.
Just one question: do you prefer to do it yourself by means of a pull request, so that you can appears as a contributor of the repo, or do you prefer I will do it myself?

**Comment by Hetari** [comment]
It's totally fine if you add it to the right category yourself @toolleeo . I'm actually a bit confused about the categories, so it's probably easier if you do it. 😄

Thank you.

**Comment by Hetari** [comment]
I'll do it, thanks
