### ISSUE TITLE
nbpreview: Terminal viewer for Jupyter notebooks.

### ISSUE THREAD

**Issue by vvatikiotis** [toolleeo/cli-apps#85]
name: nbpreview
homepage: https://github.com/paw-lu/nbpreview
git: https://github.com/paw-lu/nbpreview.git
description: A terminal viewer for Jupyter notebooks. It's like [cat](https://man7.org/linux/man-pages/man1/cat.1.html) for ipynb files.

**Comment by toolleeo** [comment]
Added. Many thanks.
