### ISSUE TITLE
breath practice exercise app

### ISSUE THREAD

**Issue by jaroslaw-weber** [toolleeo/cli-apps#88]
name: calm-garden-cli
git: https://github.com/jaroslaw-weber/calm-garden-cli
description: A small, discreet terminal tool for breath exercises with progression: earn coins, buy plants, and upgrade your garden.

**Comment by toolleeo** [comment]
Hi, nice suggestion.
Do you want to go with a pull request and get credits for the addition, or do you prefer that I will add the item?
In the former case, please edit the apps.csv file properly.
